name: changelog
permissions: write-all
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  changelog:
    uses: ./.github/workflows/workflow.yml
    secrets: inherit
    with:
      branch: 'main'