name: CHANGELOG

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      GITHUB:
        required: false
        description: 'PAT of the user to run the jobs.'

jobs:
  create_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB }}

      - name: Get previous tag
        id: previous_tag
        run: |
          tags=$(git tag --sort=-creatordate)
          echo "Found tags:"
          echo "$tags"
          current_tag="${{ github.ref_name }}"
          echo "Current tag: $current_tag"
          prev_tag=$(echo "$tags" | grep -v "^${current_tag}$" | head -n 1 || echo "")
          echo "Previous tag: $prev_tag"
          echo "prev_tag=$prev_tag" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB }}
          fromTag: ${{ steps.previous_tag.outputs.prev_tag }}
          toTag: ${{ github.ref_name }}
          writeToFile: true
          changelogFilePath: CHANGELOG.md
          includeRefIssues: true
          useGitmojis: true
          includeInvalidCommits: false
          reverseOrder: false

      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ inputs.branch }}
          commit_user_name: clouddrove-ci
          commit_user_email: 84795582+clouddrove-ci@users.noreply.github.com
          commit_author: CloudDrove CI <84795582+clouddrove-ci@users.noreply.github.com>
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md


##########